import os

POSTGRES_CONNECTION_STRING_ASYNC = os.getenv('POSTGRES_CONNECTION_STRING_ASYNC')
LINE_PROVIDER_API_BASE = os.getenv('LINE_PROVIDER_API_BASE')
BET_MAKER_API_BASE = os.getenv('BET_MAKER_API_BASE')